baseURL = "https://data-berlin-meetup.github.io/"
languageCode = "en-us"
title = "Data Berlin Meetup"
theme = "hugo-theme-meetup"

[params]
  description = "Connecting data enthusiasts in Berlin"
  author = "Data Berlin Meetup"
  github = "data-berlin-meetup"
  meetup = "data-berlin-meetup"
  twitter = "databerlin"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10
  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events"
    weight = 20
  [[menu.main]]
    identifier = "community"
    name = "Community"
    url = "/community"
    weight = 30
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 40 